// Automatically generated by the res2go, do not edit.

package mqtt_settings

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_mqtt_settings struct {
	*vcl.TForm
	Edt_host   *vcl.TLabeledEdit
	Edt_port   *vcl.TLabeledEdit
	Edt_user   *vcl.TLabeledEdit
	Edt_pwd    *vcl.TLabeledEdit
	Panel1     *vcl.TPanel
	Btn_save   *vcl.TBitBtn
	Btn_cancel *vcl.TBitBtn

	// ::private::
	TFrm_mqtt_settingsFields
}

var Frm_mqtt_settings *TFrm_mqtt_settings

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_mqtt_settings)

func NewFrm_mqtt_settings(owner vcl.IComponent) (root *TFrm_mqtt_settings) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmMqtt.gfm
var Frm_mqtt_settingsBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_mqtt_settings, &Frm_mqtt_settingsBytes)
