// Automatically generated by the res2go, do not edit.

package frm_logger

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_logger_settings struct {
	*vcl.TForm
	Panel1       *vcl.TPanel
	Btn_save     *vcl.TBitBtn
	Btn_cancel   *vcl.TBitBtn
	Edt_age      *vcl.TSpinEdit
	Lbl_age      *vcl.TLabel
	Edt_log_path *vcl.TEdit
	Lbl_path     *vcl.TLabel
	Ckb_compress *vcl.TCheckBox
	Lbl_compress *vcl.TLabel
	Cmb_level    *vcl.TComboBox
	Lbl_level    *vcl.TLabel
	Lbl_backups  *vcl.TLabel
	Edt_backups  *vcl.TSpinEdit

	// ::private::
	TFrm_logger_settingsFields
}

var Frm_logger_settings *TFrm_logger_settings

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_logger_settings)

func NewFrm_logger_settings(owner vcl.IComponent) (root *TFrm_logger_settings) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmLogger.gfm
var Frm_logger_settingsBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_logger_settings, &Frm_logger_settingsBytes)
