// Automatically generated by the res2go, do not edit.

package home

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrm_pitaya struct {
	*vcl.TForm
	StatusBar            *vcl.TStatusBar
	Pnl_header           *vcl.TPanel
	Btn_server_run       *vcl.TBitBtn
	LblServerName        *vcl.TLabel
	LV_table_data        *vcl.TListView
	MainMenu             *vcl.TMainMenu
	MenuItem1            *vcl.TMenuItem
	Menu_logger_settings *vcl.TMenuItem
	Menu_mqtt_settings   *vcl.TMenuItem
	MenuItem5            *vcl.TMenuItem
	MenuItemAbout        *vcl.TMenuItem
	ImgList              *vcl.TImageList
	Timer                *vcl.TTimer
	TrayIcon             *vcl.TTrayIcon
	PopMenu              *vcl.TPopupMenu
	PopMShow             *vcl.TMenuItem
	PopMClose            *vcl.TMenuItem
	Menu_project_list    *vcl.TMenuItem

	// ::private::
	TFrm_pitayaFields
}

var Frm_pitaya *TFrm_pitaya

// Loaded in bytes.
// vcl.Application.CreateForm(&Frm_pitaya)

func NewFrm_pitaya(owner vcl.IComponent) (root *TFrm_pitaya) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmPitaya.gfm
var Frm_pitayaBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(Frm_pitaya, &Frm_pitayaBytes)
