// Automatically generated by the res2go, do not edit.

package home

import (
    "github.com/ying32/govcl/vcl"
    _ "embed"
)

type TFrmPitaya struct {
    *vcl.TForm
    StatusBar              *vcl.TStatusBar
    GroupBox1              *vcl.TGroupBox
    MmoRunLog              *vcl.TMemo
    Panel1                 *vcl.TPanel
    BtnClearLog            *vcl.TBitBtn
    GroupBox2              *vcl.TGroupBox
    BtnServerRun           *vcl.TBitBtn
    LblServerName          *vcl.TLabel
    LblServerStartTime     *vcl.TLabel
    MainMenu               *vcl.TMainMenu
    MenuItem1              *vcl.TMenuItem
    MenuItemServerSettings *vcl.TMenuItem
    MenuItem5              *vcl.TMenuItem
    MenuItemAbout          *vcl.TMenuItem
    ImgList                *vcl.TImageList
    Timer                  *vcl.TTimer
    TrayIcon               *vcl.TTrayIcon
    PopMenu                *vcl.TPopupMenu
    PopMShow               *vcl.TMenuItem
    PopMClose              *vcl.TMenuItem
    Menu_mqtt_settings     *vcl.TMenuItem

    // ::private::
    TFrmPitayaFields
}

var FrmPitaya *TFrmPitaya




// Loaded in bytes.
// vcl.Application.CreateForm(&FrmPitaya)

func NewFrmPitaya(owner vcl.IComponent) (root *TFrmPitaya)  {
    vcl.CreateResForm(owner, &root)
    return
}

//go:embed FrmPitaya.gfm
var FrmPitayaBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmPitaya, &FrmPitayaBytes)
