// Automatically generated by the res2go, do not edit.

package settings

import (
	_ "embed"

	"github.com/ying32/govcl/vcl"
)

type TFrmPitayaSettings struct {
	*vcl.TForm
	Panel1          *vcl.TPanel
	BtnSave         *vcl.TBitBtn
	BtnCancel       *vcl.TBitBtn
	GroupBox1       *vcl.TGroupBox
	EdtCron         *vcl.TEdit
	Label1          *vcl.TLabel
	GroupBox2       *vcl.TGroupBox
	EdtShowLogCount *vcl.TSpinEdit
	Label2          *vcl.TLabel
	EdtLogPath      *vcl.TEdit
	Label3          *vcl.TLabel
	CkbCompress     *vcl.TCheckBox
	Label4          *vcl.TLabel
	CmbLevel        *vcl.TComboBox
	Label5          *vcl.TLabel

	// ::private::
	TFrmPitayaSettingsFields
}

var FrmPitayaSettings *TFrmPitayaSettings

// Loaded in bytes.
// vcl.Application.CreateForm(&FrmPitayaSettings)

func NewFrmPitayaSettings(owner vcl.IComponent) (root *TFrmPitayaSettings) {
	vcl.CreateResForm(owner, &root)
	return
}

//go:embed FrmPitayaSettings.gfm
var FrmPitayaSettingsBytes []byte

// 注册窗口资源
var _ = vcl.RegisterFormResource(FrmPitayaSettings, &FrmPitayaSettingsBytes)
